const PDFDocument = require('pdfkit');

/**
 * Generate a PDF threat intelligence report
 */
function generateThreatReport(threatData, res) {
  const doc = new PDFDocument({ margin: 50 });
  
  // Set response headers
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="threat-report-${threatData.query}-${Date.now()}.pdf"`);

  doc.pipe(res);

  // Header
  doc.fontSize(20).text('Threat Intelligence Report', { align: 'center' });
  doc.moveDown();
  doc.fontSize(12).text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' });
  doc.moveDown(2);

  // Query Information
  doc.fontSize(16).text('Query Information', { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(12);
  doc.text(`Query: ${threatData.query}`);
  doc.text(`Type: ${threatData.type.toUpperCase()}`);
  doc.text(`Timestamp: ${threatData.timestamp}`);
  doc.moveDown();

  // Risk Assessment
  doc.fontSize(16).text('Risk Assessment', { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(12);
  doc.text(`Risk Level: ${threatData.aggregated.riskLevel}`);
  doc.text(`Risk Score: ${threatData.aggregated.riskScore}/100`);
  doc.text(`Total Detections: ${threatData.aggregated.detections}`);
  doc.text(`Sources Checked: ${threatData.aggregated.totalSources}`);
  doc.moveDown();

  // Threats
  if (threatData.aggregated.threats.length > 0) {
    doc.fontSize(16).text('Identified Threats', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12);
    threatData.aggregated.threats.forEach(threat => {
      doc.text(`• ${threat}`);
    });
    doc.moveDown();
  }

  // VirusTotal Results
  if (threatData.sources.virustotal && !threatData.sources.virustotal.error) {
    doc.fontSize(16).text('VirusTotal Analysis', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12);
    const vt = threatData.sources.virustotal;
    if (vt.found) {
      doc.text(`Detection Rate: ${vt.detectionRate}%`);
      doc.text(`Positive Detections: ${vt.malicious}/${vt.total}`);
      if (vt.country) doc.text(`Country: ${vt.country}`);
      if (vt.organization) doc.text(`Organization: ${vt.organization}`);
    } else {
      doc.text('No threats detected by VirusTotal');
    }
    doc.moveDown();
  }

  // Shodan Results
  if (threatData.sources.shodan && !threatData.sources.shodan.error) {
    doc.fontSize(16).text('Shodan Analysis', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12);
    const shodan = threatData.sources.shodan;
    if (shodan.found !== false) {
      doc.text(`Location: ${shodan.city || 'Unknown'}, ${shodan.country || 'Unknown'}`);
      doc.text(`Organization: ${shodan.organization || 'Unknown'}`);
      doc.text(`Open Ports: ${shodan.ports && Array.isArray(shodan.ports) ? shodan.ports.join(', ') : 'None'}`);
      doc.text(`Services: ${shodan.services && Array.isArray(shodan.services) ? shodan.services.length : 0}`);
      if (shodan.vulns && Array.isArray(shodan.vulns) && shodan.vulns.length > 0) {
        doc.text(`Vulnerabilities Found: ${shodan.vulns.length}`);
      }
    } else {
      doc.text(shodan.message || 'No data available from Shodan');
    }
    doc.moveDown();
  }

  // AbuseIPDB Results
  if (threatData.sources.abuseipdb && !threatData.sources.abuseipdb.error) {
    doc.fontSize(16).text('AbuseIPDB Analysis', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12);
    const abuse = threatData.sources.abuseipdb;
    doc.text(`Abuse Confidence Score: ${abuse.abuseConfidenceScore}/100`);
    doc.text(`Total Reports: ${abuse.totalReports}`);
    doc.text(`Distinct Users Reporting: ${abuse.numDistinctUsers}`);
    doc.text(`Country: ${abuse.countryName || 'Unknown'}`);
    doc.text(`ISP: ${abuse.isp || 'Unknown'}`);
    if (abuse.isTor) doc.text('⚠️ Tor Exit Node Detected');
    doc.moveDown();
  }

  // Footer
  doc.fontSize(10)
     .text('This report was generated by the Real-Time Threat Intelligence Dashboard', 50, doc.page.height - 50, {
       align: 'center',
       width: doc.page.width - 100
     });

  doc.end();
}

module.exports = {
  generateThreatReport
};

